WebAnnuityCalculator/Models/CalculatorViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAnnuityCalculator.Models
{
    /// <summary>
    /// View Model калькулятора и раширеного калькулятора
    /// </summary>
    public class CalculatorViewModel
    {
        /// <summary>
        /// Сумма займа
        /// </summary>
        [Required(ErrorMessage = "Введите сумму займа")]
        [Range(1000, 10000000, ErrorMessage = "Сумма займа должна быть от 1 000 до 10 000 000")]
        public decimal LoanAmount { get; set; } = 1000;

        /// <summary>
        /// Cрок займа в месяцах
        /// Максимум 30 лет
        /// </summary>
        [Required(ErrorMessage = "Введите cрок займа в месяцах")]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "Введите целое число больше 0")]
        [Range(1, 10950, ErrorMessage = "Cрок займа должен быть от 1 до 10950 (30 лет) дней")]
        public int LoanTermDays { get; set; } = 1;

        /// <summary>
        ///  Cрок займа в днях
        ///  Максимум 30 лет
        /// </summary>
        [Required(ErrorMessage = "Введите cрок займа в днях")]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "Введите целое число больше 0")]
        [Range(1, 360, ErrorMessage = "Cрок займа должен быть от 1 до 360 (30 лет)  месяцев")]
        public int LoanTermMonths { get; set; } = 1;

        /// <summary>
        /// Шаг платежа в днях
        /// </summary>
        [Required(ErrorMessage = "Введите шаг платежа")]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "Введите целое число больше 0")]
        [Range(1, 365, ErrorMessage = "Шаг платежа должен быть от 1 до 365 дней")]
        public int PaymentStep { get; set; } = 1;

        /// <summary>
        /// Процентная ставка годовая
        /// </summary>
        [Required(ErrorMessage = "Введите ставку")]
        [Range(1, 100, ErrorMessage = "Ставка должна быть от 1 до 100 процентов")]
        public decimal LoanRateYearly { get; set; } = 1;

        /// <summary>
        /// Процентная ставка дневная,
        /// 0.00273 -  1% в год,
        /// 0.28 - 100% в год
        /// </summary>
        [Required(ErrorMessage = "Введите ставку")]
        [Range(0.00273, 0.28, ErrorMessage = "Ставка должна быть от 0.00273% (1% в год) до 0.28% (100% в год)")]

        public decimal LoanRateDayly { get; set; } = 0.00273M;

        /// <summary>
        /// Является ли расширенным калькулятором
        /// </summary>
        public bool IsExtended { get; set; } = false;
    }
}

WebAnnuityCalculator/Models/ResultViewModel.cs
namespace WebAnnuityCalculator.Models
{
    /// <summary>
    /// View Model результата стандартного или расширенного калькулятора
    /// </summary>
    public class ResultViewModel
    {
        /// <summary>
        /// Список платежей
        /// </summary>
        public List<Payment> Payments { get; set; }

        /// <summary>
        /// Всего платежей
        /// </summary>
        public decimal TotalPayments { get; set; }

        /// <summary>
        /// Всего переплат
        /// </summary>
        public decimal Overpayment { get;  set; }

        public ResultViewModel()
        {
            Payments = new List<Payment>();
        }
    }
}

WebAnnuityCalculator/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebAnnuityCalculator.Models;
using WebAnnuityCalculator.Services.CalculatorService;

namespace WebAnnuityCalculator.Controllers
{
    public class CalculatorController : Controller
    {
        private readonly ICalculatorService _calculatorService;

        public CalculatorController(ICalculatorService calculatorService)
        {
            _calculatorService = calculatorService;
        }

        [HttpGet]
        public IActionResult Calculator(bool isExtended = false)
        {
            CalculatorViewModel calculatorVM = new CalculatorViewModel();
            if (isExtended)
            {
                calculatorVM.IsExtended = true;
            }
            return View(calculatorVM);
        }

        [HttpPost]
        public IActionResult Calculator(CalculatorViewModel calculatorVM)
        {
            if(ModelState.IsValid)
            {
                if (calculatorVM.IsExtended)
                {
                    return RedirectToAction("ResultExtended", calculatorVM);
                }
                return RedirectToAction("Result", calculatorVM);
            }            
            return View(calculatorVM);
        }

        //Результат стандартного калькулятора
        public IActionResult Result(CalculatorViewModel calculatorVM)
        {
            // Сумма долга
            decimal loanAmount = calculatorVM.LoanAmount;
            // Годовая процентная ставка
            decimal yearlyInterest = calculatorVM.LoanRateYearly / 100;
            // Месячная процентная ставка по кредиту 
            decimal mounthlyInterest = yearlyInterest / 12;
            // Количество периодов, в течение которых выплачивается кредит.
            int paymentsNumber = calculatorVM.LoanTermMonths;

            ResultViewModel result = 
                _calculatorService.Calculate(loanAmount,mounthlyInterest,paymentsNumber,0,true);

            return View(result);
        }

        //Результат расширенного калькулятора
        public IActionResult ResultExtended(CalculatorViewModel calculatorVM)
        {
            // Сумма долга
            decimal loanAmount = calculatorVM.LoanAmount;
            // Дневная процентная ставка
            decimal dailyInterest = calculatorVM.LoanRateDayly / 100;
            // Количество периодов, в течение которых выплачивается кредит.
           int paymentsNumber = calculatorVM.LoanTermDays / calculatorVM.PaymentStep;
            // Ставка за период
            decimal stepInterest = dailyInterest * calculatorVM.PaymentStep;
            // Шаг платежей
            int paymentStep = calculatorVM.PaymentStep;

            ResultViewModel result = 
                _calculatorService.Calculate(loanAmount,stepInterest,paymentsNumber,paymentStep,false);
            
            return View("Result",result);
        }      


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }


}

WebAnnuityCalculator/Views/Calculator/Calculator.cshtml
@model CalculatorViewModel
@{
    if (Model.IsExtended)
    {
        ViewData["Title"] = "Расширенный калькулятор";
    }
    else
    {
        ViewData["Title"] = "Калькулятор аннуитетных платежей";
    }
}

<h1 class="text-center">@ViewData["Title"]</h1>
<div class="container-xl mt-3">
    <form asp-controller="Calculator" asp-action="Calculator" method="post">
        <div class="d-flex justify-content-center">
            <div class="col-10 col-sm-6 col-md-3 d-flex flex-column">

                <label class="form-label">Сумма займа</label>
                <input class="form-control" type="number" asp-for="LoanAmount" />
                <span asp-validation-for="LoanAmount" class="text-danger mt-2"></span>

                @if (!Model.IsExtended)
                {
                    @*Standart Calculator*@
                    <label class="mt-3 form-label">Срок займа в месяцах</label>
                    <input class="form-control" type="number" asp-for="LoanTermMonths" />
                    <span asp-validation-for="LoanTermMonths" class="text-danger mt-2"></span>

                    <label class="mt-3 form-label">Ставка в год</label>
                    <input class="form-control" type="number" asp-for="LoanRateYearly" />
                    <span asp-validation-for="LoanRateYearly" class="text-danger mt-2"></span>
                }
                else
                {
                    @*Extended calculator*@
                    <label class="mt-3 form-label">Срок займа в днях</label>
                    <input class="form-control" type="number" asp-for="LoanTermDays" />
                    <span asp-validation-for="LoanTermDays" class="text-danger mt-2"></span>

                    <label class="mt-3 form-label">Ставка в день</label>
                    <input class="form-control" type="number" asp-for="LoanRateDayly" />
                    <span asp-validation-for="LoanRateDayly" class="text-danger mt-2"></span>

                    <label class="mt-3 form-label">Шаг платежа в днях</label>
                    <input class="form-control" type="number" asp-for="PaymentStep" />
                    <span asp-validation-for="PaymentStep" class="text-danger mt-2"></span>

                    <input type="hidden" asp-for="IsExtended" value="true"/>
                }

                <button class="mt-3 btn btn-primary" type="submit">Рассчитать</button>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

WebAnnuityCalculator/Views/Calculator/Result.cshtml
@model ResultViewModel
@{
    ViewData["Title"] = "Результат";
}

<h1 class="text-center">@ViewData["Title"]</h1>
<div class="container-xl mt-3">
    <table class="mt-3 table table-bordered">
        <thead>
            <tr>
                <th scope="col">№</th>
                <th scope="col">Дата платежа</th>
                <th scope="col">Сумма платежа</th>
                <th scope="col">Основной долг</th>
                <th scope="col">Проценты</th>
                <th scope="col">Остаток долга</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Payments)
            {
                <tr>
                    <th scope="row">@{int number = Model.Payments.IndexOf(item) + 1;} @number</th>
                    <td>@item.Date</td>
                    <td>@item.AnnuityPayment.ToString("0.00")</td>
                    <td>@item.BodyPayment.ToString("0.00")</td>
                    <td>@item.InterestPayment.ToString("0.00")</td>
                    <td>@item.LoanBalance.ToString("0.00")</td>
                </tr>
            }

            <tr>
                <th scope="row"></th>
                <td></td>
                <td>Всех платежей</td>
                <td>@Model.TotalPayments.ToString("0.00")</td>
                <td>Всего переплат</td>
                <td>@Model.Overpayment.ToString("0.00")</td>
            </tr>

        </tbody>
    </table>
</div>